// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  vy: __t.f32(),
  left: __t.bool(),
  right: __t.bool(),
  jump: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

